package oleacc

const (
	ROLE_SYSTEM_TITLEBAR = iota
	ROLE_SYSTEM_MENUBAR
	ROLE_SYSTEM_SCROLLBAR
	ROLE_SYSTEM_GRIP
	ROLE_SYSTEM_SOUND
	ROLE_SYSTEM_CURSOR
	ROLE_SYSTEM_CARET
	ROLE_SYSTEM_ALERT
	ROLE_SYSTEM_WINDOW
	ROLE_SYSTEM_CLIENT
	ROLE_SYSTEM_MENUPOPUP
	ROLE_SYSTEM_MENUITEM
	ROLE_SYSTEM_TOOLTIP
	ROLE_SYSTEM_APPLICATION
	ROLE_SYSTEM_DOCUMENT
	ROLE_SYSTEM_PANE
	ROLE_SYSTEM_CHART
	ROLE_SYSTEM_DIALOG
	ROLE_SYSTEM_BORDER
	ROLE_SYSTEM_GROUPING
	ROLE_SYSTEM_SEPARATOR
	ROLE_SYSTEM_TOOLBAR
	ROLE_SYSTEM_STATUSBAR
	ROLE_SYSTEM_TABLE
	ROLE_SYSTEM_COLUMNHEADER
	ROLE_SYSTEM_ROWHEADER
	ROLE_SYSTEM_COLUMN
	ROLE_SYSTEM_ROW
	ROLE_SYSTEM_CELL
	ROLE_SYSTEM_LINK
	ROLE_SYSTEM_HELPBALLOON
	ROLE_SYSTEM_CHARACTER
	ROLE_SYSTEM_LIST
	ROLE_SYSTEM_LISTITEM
	ROLE_SYSTEM_OUTLINE
	ROLE_SYSTEM_OUTLINEITEM
	ROLE_SYSTEM_PAGETAB
	ROLE_SYSTEM_PROPERTYPAGE
	ROLE_SYSTEM_INDICATOR
	ROLE_SYSTEM_GRAPHIC
	ROLE_SYSTEM_STATICTEXT
	ROLE_SYSTEM_TEXT
	ROLE_SYSTEM_PUSHBUTTON
	ROLE_SYSTEM_CHECKBUTTON
	ROLE_SYSTEM_RADIOBUTTON
	ROLE_SYSTEM_COMBOBOX
	ROLE_SYSTEM_DROPLIST
	ROLE_SYSTEM_PROGRESSBAR
	ROLE_SYSTEM_DIAL
	ROLE_SYSTEM_HOTKEYFIELD
	ROLE_SYSTEM_SLIDER
	ROLE_SYSTEM_SPINBUTTON
	ROLE_SYSTEM_DIAGRAM
	ROLE_SYSTEM_ANIMATION
	ROLE_SYSTEM_EQUATION
	ROLE_SYSTEM_BUTTONDROPDOWN
	ROLE_SYSTEM_BUTTONMENU
	ROLE_SYSTEM_BUTTONDROPDOWNGRID
	ROLE_SYSTEM_WHITESPACE
	ROLE_SYSTEM_PAGETABLIST
	ROLE_SYSTEM_CLOCK
	ROLE_SYSTEM_SPLITBUTTON
	ROLE_SYSTEM_IPADDRESS
	ROLE_SYSTEM_OUTLINEBUTTON
)

const (
	STATE_SYSTEM_NORMAL          = 0x0
	STATE_SYSTEM_UNAVAILABLE     = 0x1
	STATE_SYSTEM_SELECTED        = 0x2
	STATE_SYSTEM_FOCUSED         = 0x4
	STATE_SYSTEM_PRESSED         = 0x8
	STATE_SYSTEM_CHECKED         = 0x10
	STATE_SYSTEM_MIXED           = 0x20
	STATE_SYSTEM_INDETERMINATE   = STATE_SYSTEM_MIXED
	STATE_SYSTEM_READONLY        = 0x40
	STATE_SYSTEM_HOTTRACKED      = 0x80
	STATE_SYSTEM_DEFAULT         = 0x100
	STATE_SYSTEM_EXPANDED        = 0x200
	STATE_SYSTEM_COLLAPSED       = 0x400
	STATE_SYSTEM_BUSY            = 0x800
	STATE_SYSTEM_FLOATING        = 0x1000
	STATE_SYSTEM_MARQUEED        = 0x2000
	STATE_SYSTEM_ANIMATED        = 0x4000
	STATE_SYSTEM_INVISIBLE       = 0x8000
	STATE_SYSTEM_OFFSCREEN       = 0x10000
	STATE_SYSTEM_SIZEABLE        = 0x20000
	STATE_SYSTEM_MOVEABLE        = 0x40000
	STATE_SYSTEM_SELFVOICING     = 0x80000
	STATE_SYSTEM_FOCUSABLE       = 0x100000
	STATE_SYSTEM_SELECTABLE      = 0x200000
	STATE_SYSTEM_LINKED          = 0x400000
	STATE_SYSTEM_TRAVERSED       = 0x800000
	STATE_SYSTEM_MULTISELECTABLE = 0x1000000
	STATE_SYSTEM_EXTSELECTABLE   = 0x2000000
	STATE_SYSTEM_ALERT_LOW       = 0x4000000
	STATE_SYSTEM_ALERT_MEDIUM    = 0x8000000
	STATE_SYSTEM_ALERT_HIGH      = 0x10000000
	STATE_SYSTEM_PROTECTED       = 0x20000000
	STATE_SYSTEM_VALID           = 0x7fffffff
)

const (
	NAVDIR_MIN = iota
	NAVDIR_UP
	NAVDIR_DOWN
	NAVDIR_LEFT
	NAVDIR_RIGHT
	NAVDIR_NEXT
	NAVDIR_PREVIOUS
	NAVDIR_FIRSTCHILD
	NAVDIR_LASTCHILD
	NAVDIR_MAX
)
